name: Update Filtered EPG

on:
  schedule:
    - cron: "0 12 * * *" # Runs daily at 12:00 PM UTC (01:00 AM NZT during daylight savings)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download EPG XML from Provided URL
      run: |
        wget -O epg.xml.gz https://github.com/anilwee/dialog/raw/refs/heads/main/public/epg.xml.gz

    - name: Verify File Download
      run: |
        if [ ! -f "epg.xml.gz" ]; then
          echo "ERROR: epg.xml.gz not found!"
          exit 1
        fi
        echo "File downloaded successfully."
        gzip -t epg.xml.gz || { echo "ERROR: epg.xml.gz is corrupted!"; exit 1; }

    - name: Move EPG File
      run: |
        mkdir -p public
        cp epg.xml.gz public/

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run the filter script
      run: python filter_epg.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add dialog.xml
        git commit -m "Update filtered EPG"
        git push
