name: Update EPG

on:
  schedule:
    - cron: "0 12 * * *"  # 00:00 AKL/NZ time (12:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install xml.etree.ElementTree

      - name: Run Extraction and Filtering
        env:
          CRITICAL_LINK: ${{ secrets.CRITICAL_LINK }}
        run: python filter_epg.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dialog.xml
          git commit -m "Updated dialog.xml" || echo "No changes to commit"
          git push
