name: Filter and Upload EPG

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  process-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests xmltodict

      - name: Fetch and Filter EPG
        env:
          CRITICAL_LINK: ${{ secrets.CRITICAL_LINK }}
        run: |
          curl -L $CRITICAL_LINK -o epg.xml.gz
          gzip -d epg.xml.gz
          python filter_epg.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add dialog.xml
          git commit -m "Update filtered EPG"
          git push
