name: Update Filtered EPG

on:
  schedule:
    - cron: "0 12 * * *" # Runs daily at 12:00 PM UTC (01:00 AM NZT during daylight savings)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download EPG XML from Public URL
      run: |
        wget -O epg.xml ${{ secrets.CRITICAL_LINK }}

    - name: Verify Downloaded File
      run: |
        echo "Checking file details:"
        ls -lh epg.xml
        echo "First 20 lines of the XML file:"
        head -n 20 epg.xml

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run the filter script
      run: python filter_epg.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add dialog.xml
        git commit -m "Update filtered EPG"
        git push
