name: Update Filtered EPG

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}

    - name: Copy epg.xml.gz from public directory
      run: |
        mkdir -p public
        cp public/epg.xml.gz public/epg.xml.gz

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run the filter script
      run: python filter_epg.py

    - name: Validate Output
      run: |
        if [ ! -f "dialog.xml" ]; then
          echo "ERROR: Output file dialog.xml not generated!"
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add dialog.xml
        git commit -m "Update filtered EPG"
        git push
