name: Update Filtered EPG

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git for Authentication
      run: |
        echo "machine github.com" > ~/.netrc
        echo "login ${{ secrets.PRIVATE_REPO_TOKEN }}" >> ~/.netrc
        echo "password ${{ secrets.PRIVATE_REPO_TOKEN }}" >> ~/.netrc

    - name: Download or Generate epg.xml.gz
      run: |
        if [ ! -f "public/epg.xml.gz" ]; then
          echo "Downloading epg.xml.gz..."
          curl -o public/epg.xml.gz http://example.com/epg.xml.gz
        fi

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run the filter script
      run: python filter_epg.py

    - name: Validate Output
      run: |
        if [ ! -f "dialog.xml" ]; then
          echo "ERROR: Output file dialog.xml not generated!"
          exit 1
        fi

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add dialog.xml
        git commit -m "Update filtered EPG"
        git push
