jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download EPG XML from Public URL
      run: |
        wget -O epg.xml.gz ${{ secrets.CRITICAL_LINK }}

    - name: Verify XML Integrity
      run: |
        gzip -d epg.xml.gz
        xmllint epg.xml --noout || (echo "Invalid XML file detected!" && exit 1)

    - name: Move EPG File
      run: |
        mkdir -p public
        cp epg.xml.gz public/

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run the filter script
      run: python filter_epg.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add dialog.xml
        git commit -m "Update filtered EPG" || echo "No changes to commit"
        git push
