name: Filter and Upload EPG

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  process-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install lxml

      - name: Download EPG File
        env:
          CRITICAL_LINK: ${{ secrets.CRITICAL_LINK }}
        run: |
          # Download the file
          curl -L $CRITICAL_LINK -o epg.xml.gz

      - name: Check File Type and Decompress if Necessary
        run: |
          # Check if the file is gzip format
          if file epg.xml.gz | grep -q 'gzip compressed data'; then
            echo "File is in gzip format. Decompressing..."
            gzip -d epg.xml.gz
          else
            echo "File is not in gzip format. Renaming..."
            mv epg.xml.gz epg.xml
          fi

      - name: Debug EPG File
        run: |
          echo "Inspecting the first 30 lines of the XML file:"
          head -n 30 epg.xml
          echo "Validating XML file:"
          xmllint --noout epg.xml || echo "XML validation failed"

      - name: Filter the EPG File
        run: python src/filter_xml.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add public/dialog.xml
          git commit -m "Update filtered EPG"
          git push
